apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fairmed-ingress
  namespace: fairmed
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: api.fairmed.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fairmed-api
                port:
                  number: 80
