apiVersion: v1
kind: Service
metadata:
  name: fairmed-api
  namespace: fairmed
spec:
  selector:
    app: fairmed-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
